# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            WriteOnly.pl
tagline:          WriteOnly Scala Blog
description:      "Blog tylko-do-zapisu o jÄ™zykach programowania Scala/JVM, Scala.js i Scala Native"
url:              https://writeonly.pl/
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Karlo Espiritu
  url:            https://twitter.com/karloespiritu

paginate:         2
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
#  - jekyll-twitter-plugin

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/karloespiritu/blackdoc
